# Generated by Django 5.1.7 on 2025-03-26 21:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top3health', '0004_mydailylog_breakfast_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myexpenses',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.CreateModel(
            name='Mymonthlyexpenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('family_eatout_count', models.IntegerField(blank=True, null=True)),
                ('weekly_eatout_cost', models.IntegerField(blank=True, null=True)),
                ('family_grocery_count', models.IntegerField(blank=True, null=True)),
                ('weekly_grocery_cost', models.IntegerField(blank=True, null=True)),
                ('Misc_expense_member', models.IntegerField(blank=True, null=True)),
                ('Misc_expenses', models.IntegerField(blank=True, null=True)),
                ('family_premium_count', models.IntegerField(blank=True, null=True)),
                ('insurance_premium', models.IntegerField(blank=True, null=True)),
                ('members_for_office_visit', models.IntegerField(blank=True, null=True)),
                ('office_visit_cost', models.IntegerField(blank=True, null=True)),
                ('members_for_prescriptions', models.IntegerField(blank=True, null=True)),
                ('prescription_cost', models.IntegerField(blank=True, null=True)),
                ('members_for_oop', models.IntegerField(blank=True, null=True)),
                ('oop_cost', models.IntegerField(blank=True, null=True)),
                ('members_for_gym', models.IntegerField(blank=True, null=True)),
                ('gym_cost', models.IntegerField(blank=True, null=True)),
                ('customuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
