# Generated by Django 5.1.5 on 2025-03-04 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top3health', '0002_alter_mydailylog_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mydailylog',
            name='balance_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mydailylog',
            name='moderate_intensity_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mydailylog',
            name='muscle_build_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mydailylog',
            name='vigorous_intensity_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
