# Generated by Django 5.1.5 on 2025-03-12 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top3health', '0003_mydailylog_balance_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mydailylog',
            name='Breakfast_description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='mydailylog',
            name='Breakfast_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mydailylog',
            name='Dinner_description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='mydailylog',
            name='Dinner_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mydailylog',
            name='Lunch_description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='mydailylog',
            name='Lunch_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
