"""
Django settings for healthcare project.

Generated by 'django-admin startproject' using Django 4.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

print(BASE_DIR)
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-+&5a8s%_4p&r7qlgf-#swc48g!kfp8wj@^oy1td6d!lf!xm2su'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

#ALLOWED_HOSTS = ['localhost', '127.0.0.1', [*]]
ALLOWED_HOSTS = ['*','localhost', '127.0.0.1','*', 'https://cfa6-65-36-96-235.ngrok-free.app',  ]
#ALLOWED_HOSTS = ['*', 'localhost', '127.0.0.1',  ]

# Application definition

INSTALLED_APPS = [
    'corsheaders',
    # 'django-admin-tools',
    'django.contrib.admin',
    'admin_tools.dashboard',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'top3health',
    'crispy_forms',
    'crispy_bootstrap4',
    'rest_framework',
]

CORS_ALLOW_HEADERS = [
'accept',
'accept-encoding',
'authorization',
'content-type',
'dnt',
'origin',
'user-agent',
'x-csrftoken',
'x-requested-with',
]

CORS_ALLOWED_ORIGINS = [
    'http://localhost:8000',
    'https://cfa6-65-36-96-235.ngrok-free.app'
    
    
    
]

CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_METHODS = [
'DELETE',
'GET',
'OPTIONS',
'PATCH',
'POST',
'PUT',
]

CORS_ORIGIN_WHITELIST = [
    'http://localhost:8000',
    'https://cfa6-65-36-96-235.ngrok-free.app'
    
]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]
CSRF_TRUSTED_ORIGINS = ['http://127.0.0.1:8000', 'https://cfa6-65-36-96-235.ngrok-free.app']
CRISPY_TEMPLATE_PACK = 'uni_form'
SITE_ID=1
AUTH_USER_MODEL = 'top3health.CustomUser'
MIDDLEWARE = [

   
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',


]

ROOT_URLCONF = 'healthcare.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [str(BASE_DIR.joinpath('templates'))],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'healthcare.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'top3db',
        'USER': 'girish',
        'PASSWORD': 'Mazatlan909.',
        'HOST': 'localhost',
        'PORT': '3306',
        'OPTIONS': {
            'read_default_file': '/etc/mysql/my.cnf',
    }
}}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Chicago'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [str(BASE_DIR.joinpath('static')),]
# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field



DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
LOGIN_URL = '/accounts/login'
LOGIN_REDIRECT_URL = 'landing'
LOGOUT_REDIRECT_URL = 'top3health-bootstrap'
CRISPY_TEMPLATE_PACK = 'bootstrap4'
SESSION_COOKIE_SECURE = False
SESSION_COOKIE_HTTPONLY = True
# SESSION_COOKIE_HTTPONLY = True
#SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
# SESSION_COOKIE_NAME = 'top3health'
# SESSION_COOKIE_AGE = 100
SESSION_EXPIRE_AT_BROWSER_CLOSE = False